### ISSUE TITLE
Pretty-printing exceptions

### ISSUE THREAD

**Issue by cpitclaudel** [ejgallego/coq-serapi#162]
Hi there,

Once I have an exception, such as the following, is there a way to pretty-print it?

```
(Answer query11(CoqExn(((fname ToplevelInput)(line_nb 2)(bol_pos 28)(line_nb_last 2)(bol_pos_last 28)(bp 40)(ep 41)))((2 3))(Backtrace())(ExplainErr.EvaluatedError"The term \"1\" has type \"nat\" while it is expected to have type \"Prop\".")))
```

Alternatively, is it safe to assume that `CoqExn` always include a type and a message?

Thanks!

**Comment by ejgallego** [comment]
> Once I have an exception, such as the following, is there a way to pretty-print it?

No, however this is a very good request, see #163

Unfortunately there is no way to turn a serialized exception back to its representation, not at least with the current infrastructure; [hopefully some day we add proper registration of errors to Coq], thus I added to the Exn field the pretty-printed message.

Note that exception printing has some issues in Coq, as does error handling; I have a few PRs open trying to improve this, hopefully they land in 8.11. So if you see some weird message well, that's a Coq problem.

> is it safe to assume that `CoqExn` always include a type and a message?

I am not sure what you mean but as exceptions are basically open datatypes in OCaml you can do little assumptions on them.

You could however recognize particular common error messages, such as `TypeError` and have nicer code to handle them. As of today however quite a few error messages lose their structure due to the problem pointed out above, working on it.

**Comment by ejgallego** [comment]
> is it safe to assume that `CoqExn` always include a type and a message?

I think I misread your question. After #187 `CoqExn` does always carry the following information:
```ocaml
module ExnInfo = struct
  type t =
    { loc : Loc.t option
    ; stm_ids : (Stateid.t * Stateid.t) option
    ; backtrace : Printexc.raw_backtrace
    ; exn : exn
    ; pp : Pp.t
    ; str : string
    }
end
```

**Comment by cpitclaudel** [comment]
Neat, thanks!
