### ISSUE TITLE
Unclear how to use SerAPI demo

### ISSUE THREAD

**Issue by joelburget** [ejgallego/coq-serapi#46]
It would be good for the [rhino-hawk](https://x80.org/rhino-hawk/) demo to come with instructions. Right now the only clue what to type comes from this repo's README, which starts with `(Add () "Lemma addn0 n : n + 0 = n. Proof. now induction n. Qed.")`. But, this doesn't work in the online SerAPI demo.

```lisp
> (Add () "Lemma addn0 n : n + 0 = n. Proof. now induction n. Qed.")

(Answer 0 Ack)

(Answer 0(CoqExn(((fname"")(line_nb 1)(bol_pos 0)(line_nb_last 1)(bol_pos_last 0)(bp 18)(ep 19)))()(Backtrace())(Stream.Error"'.' expected after [vernac:gallina] (in [vernac_aux])")))

(Answer 0 Completed)
```

**Comment by ejgallego** [comment]
Hi @joelburget indeed there are two problems here:

1. Coq's `Prelude` is not loaded by the web version. [hence the parsing error].
1. The documentation of the protocol itself is poor.

1. should be solved the next time I update the web build, as it was due to a limitation of the old library pre-loading API that was solved in 8.8.

Regarding point 2, documentation for the protocol is indeed incomplete as a major revision is expected for Coq 8.9. The new protocol revision will indeed pretty well documented and expected to be "stable", so I didn't bother to write a lot about the current one.

I'll try to improve the README tho. The command line help for `sertop` is a bit better in this regard.

**Comment by ejgallego** [comment]
Ok the demo is updated, most problems should be fixed. I'll also push a release build to `jscoq-builds` under the proper branch.

**Comment by joelburget** [comment]
Wonderful. Thank you!
