### ISSUE TITLE
[sertop] Message output from Add delayed to next Query

### ISSUE THREAD

**Issue by riswords** [ejgallego/coq-serapi#51]
In sertop, if I issue an Add command containing vernacular like this for example:

```
> (Add () "Check true.")
(Answer 0 Ack)
(Answer 0(Added 2((fname"")(line_nb 1)(bol_pos 0)(line_nb_last 1)(bol_pos_last 0)(bp 0)(ep 11))NewTip))
(Answer 0 Completed)
```
There is no Feedback entry for the output that would be generated by this. But if I follow this up with a Query command, then I get Feedback results for both the Add and the Query like this:
```
> (Query () (Vernac "Check 1."))
(Answer 1 Ack)
(Feedback((id 2)(route 0)(contents(ProcessingIn master))))
(Feedback((id 1)(route 0)(contents Processed)))
(Feedback((id 2)(route 0)(contents(Message Notice()(Pp_glue((Pp_tag constr.reference(Pp_string true))Pp_force_newline(Pp_string"     : ")(Pp_tag constr.reference(Pp_string bool))))))))
(Feedback((id 2)(route 0)(contents Processed)))
(Feedback((id 2)(route 0)(contents(Message Notice()(Pp_glue((Pp_string 1)Pp_force_newline(Pp_string"     : ")(Pp_tag constr.reference(Pp_string nat))))))))
(Answer 1(ObjList()))
(Answer 1 Completed)
```
You can see that in this output, I get two Messages both with the same id 2, which means that they aren't distinguishable, and only one of them is the output that corresponds to the Query.

Ideally, I would expect that the Message output for the Add command would either be included in the response from the Add, or dropped entirely, or given a different id if it must be included with a later Query.

I am using SerAPI installed via opam with ocaml 4.06.0, sertop 0.4.10, and coq (also installed with opam) 8.7.2.

**Comment by ejgallego** [comment]
Oh, I see I didn't properly explain what happens in the second case. When you do:
```lisp
(Query () (Vernac "Check 1."))
```

Coq automatically fills in the `sid` parameter with the span numbered 2. So Coq thinks that in order to check `1`, it should perform first `(Exec 2)`, hence the output.

You can use the `((route N))` parameter to `Query` in order to improve this situation. That should help you distinguish the two answers.

But note that in my view the `Vernac` + `route` query method is deprecated, (as it relies in textual input) and instead we will add typed queries (see the yet to be improved `TypeOf`) and speculative execution.

**Comment by ejgallego** [comment]
By the way, in this particular project I seriously suffer from "The Curse of Knowledge", it feels quite hard to assess how the documentation reads for others, so please don't hesitate to complain / open issues as to improve documentation; feedback is much appreciated.

**Comment by riswords** [comment]
Hi @ejgallego, I agree, this sounds like a documentation issue. I haven't been using `Exec`, but it sounds like I should be doing so after `Add`ing commands like "Check" or "Require". If I'm doing this programmatically, it sounds like the easiest/most conservative would be to always run `Exec` for each NewTip response from `Add`. For an `Add` with multiple NewTip responses, would it be sufficient to run `Exec` only for the final NewTip response?

Additionally, you said that the `Vernac` + `route` query method is deprecated. Could you clarify a little more about what specifically is deprecated? I think you're suggesting that instead of using `Query`+`Vernac`+`Check...` to check the type of an expression, I should instead use `Query`+`TypeOf` and similarly instead of `Query`+`Vernac`+`Print...`, I could instead use `Query`+`Definition`. Is that what you were suggesting?

I took a brief look at the output from TypeOf and Definition, and I think I can switch over to using those instead if that's preferred. I didn't have a reason for not using them except that I didn't know they existed. :)

Along the same lines, it occurs to me that I am also using `Query`+`Vernac`+`SearchPattern`. Is there an alternative I should be using instead of that?

**Comment by ejgallego** [comment]
> For an Add with multiple NewTip responses, would it be sufficient to run Exec only for the final NewTip response?

As of today yes, however it could well happen that in the future SerAPI / Coq gets a bit lazier and only executes what's excitedly asked to. So I'd say that the best approach is to `Exec` every span. Note that Coq won't re-execute an already `Exec` span [maybe the command should indeed be called `Check`]

In the future ranges will be added you can do `(Exec (sp1 -- sp2))` and all the spans between `sp1` and `sp2` would be checked.

Another approach is to do as jsCoq does, it uses the `newtip` `Add` parameter and then [without waiting] it `Exec`s. However, you have to give up on batch sentence splitting. The workflow in that case is:
1. choose a new span_id `nid`,
2. `(Add ((newtip nid)) "Text")`
3. `(Exec nid)` [without waiting!]
4. When the `NewTip` answer is received, update the text with the position, goto 1.

> Could you clarify a little more about what specifically is deprecated?

You did perfectly describe the situation. That method is deprecated because of technical problems with the design of the protocol, for example, the fact that you don't have control over the format of the returned object.

However the replacement "Structured Query Language" is still not ready, and the `Vernac` method won't go away in the near future, so IMHO it is safe to use for now.

> I took a brief look at the output from TypeOf and Definition, and I think I can switch over to using those instead if that's preferred. I didn't have a reason for not using them except that I didn't know they existed. :)

IMO it is be your call, I think you'd be the first person ever using them so they are untested and you will find bugs; most of them should be fixed easily so whether to use them or not depends on a) your availability or desire to test alpha features, b) your needs in term of protocol, as `TypeOf/Definition` do provide more features that the feedback-based approach.

Indeed, the main reason to use the newer forms is to avoid parsing feedback.

> Along the same lines, it occurs to me that I am also using Query+Vernac+SearchPattern. Is there an alternative I should be using instead of that?

Oh I didn't implement `Search` yet, issue created #52
