### ISSUE TITLE
Tactic expression serialization failures

### ISSUE THREAD

**Issue by palmskog** [ejgallego/coq-serapi#68]
We are aiming to try out Serapi serialization/deserialization on some large-scale Coq projects, but first we want to ensure it works correctly on some smaller projects manually. The general theme we're seeing is tactic expression serialization failures similar to #66 (arguments to tactics not being handled properly). Serialization/deserialization of pure Gallina seems to work fine.

Here are files extracted from a utility library that all generate sexps containing `"[XXX ser_gen]"`, and the respective causes:

- [clear.v](https://gist.github.com/palmskog/1374a71b81b9789388befb9c6f8347db): calling the `clear` tactic with arguments on [line 49](https://gist.github.com/palmskog/1374a71b81b9789388befb9c6f8347db#file-clear-v-L49)

- [revert.v](https://gist.github.com/palmskog/8791628d787fe73a2d413c43e43c758f): calling the `revert` tactic with arguments on [line 38](https://gist.github.com/palmskog/8791628d787fe73a2d413c43e43c758f#file-revert-v-L38)

- [subst.v](https://gist.github.com/palmskog/cca7ac935fafe19f6116c5b820ff652e): calling the `subst` tactic with arguments on [line 69](https://gist.github.com/palmskog/cca7ac935fafe19f6116c5b820ff652e#file-subst-v-L69)

- [exists.v](https://gist.github.com/palmskog/81ae50125328ec130f44a581b0e566fd): calling the `exists` tactic with argument on [line 35](https://gist.github.com/palmskog/81ae50125328ec130f44a581b0e566fd#file-exists-v-L35)

- [firstorder.v](https://gist.github.com/palmskog/6c93e01b8d3e439b3a0da7b687f292e0): calling the `firstorder` tactic without arguments on [line 67](https://gist.github.com/palmskog/6c93e01b8d3e439b3a0da7b687f292e0#file-firstorder-v-L67)

All of the failures are for Coq 8.8.2 and the latest revision of Serapi (3f67fc3).

**Comment by ejgallego** [comment]
Hi @palmskog , thanks a lot for submitting this issue, it is invaluable!!! I will be a bit slow these days due to holidays, a few comments / questions:

- this problem does happen due to the way tactics are implemented in Coq; they are a plugin that extend the parser and require some manual work so SerAPI is aware of them. The extensible parsing of Coq is indeed one of the main reasons writing a tool that can parse Coq is doomed to fail, unless you plug into the Coq AST itself as SerAPI does.

- I hope to remove the need for manual work in Coq 8.10 thanks to a new preprocessor for parsing extensions that just got added to Coq (`coqpp`). Meanwhile, 8.9 should be a bit better in that regard.

Now, a question for @palmskog : 

- 8.9beta is just hours/days away from release. Fixing this in 8.8 will be different than fixing this in 8.9. Do you think that it is feasible for you to move to 8.9, or are you planning to stay with 8.8 for a while?

If the latter, I may try to backport to 8.8 a patch that provides much better fallbacks in the case of serialization failures in plugins.

**Comment by ejgallego** [comment]
Anyways, I'm going to fix a few of those in a commit now.

**Comment by palmskog** [comment]
@ejgallego all else equal we would definitely move to the 8.9beta if that would be easier for you, since we really appreciate your help with debugging. However, we also want to be able to support a decent chunk of real-world Coq projects.

As soon as the beta is out, I will try to run it on several projects we have used before and see how they work, and then report back. I know compatibility is a higher priority nowadays (8.5 to 8.6 was a pain), so I remain hopeful.

**Comment by ejgallego** [comment]
Thanks @palmskog !

The v8.9 branch should compile again. The missing cases you reported should be fixed in both the v8.8 and v8.9 branch. I will make this last one the official soon.

Indeed, I started to develop a test-suite using your examples, I think it is a great idea.

Note that in 8.9, expressions that cannot be properly serialized will indeed throw an exception instead of silently outputting garbage. I think this makes more sense as it will allow to detect missing cases more easy, WDTY? We could make this tweakable with a flag of course.

**Comment by ejgallego** [comment]
> However, the exception throwing is not currently in the 8.9 branch, right?

It is not indeed; but I hope it will be soon as I've just submitted PR #70

**Comment by ejgallego** [comment]
I've pushed a new version of #70 , IMHO it is getting ready to merge, even if not very refined yet.

**Comment by palmskog** [comment]
@ejgallego thanks again for all fixes. I hope we can begin checking some large-scale projects soon with Coq 8.9 and serapi and will talk to my colleagues about that. However, several of these projects use `ssreflect`, and the `by` and `elim` tactics there currently give errors, as can be demonstrated using [this file](https://github.com/proofengineering/serapi-tests/blob/4f970dbc056a867a74521c009b05a997fd1cf15e/elim.v).

**Comment by ejgallego** [comment]
Thanks again @palmskog ; will fix ASAP.

We'll have to wait for 8.10 to get rid of this problem forever :/

**Comment by palmskog** [comment]
@ejgallego here is another `XXX` serialization failure, this time with the `replace` tactic: [replace.v](https://github.com/proofengineering/serapi-tests/blob/master/replace.v).

I think this is the only problem blocking us to process some large projects.

**Comment by ejgallego** [comment]
I am targeting the fix of this bug for 8.10 / SerAPI 0.7; I will consider it fixed when Coq generates the right information so SerAPI doesn't need any kind of manual registration of argument witnesses.

**Comment by ejgallego** [comment]
Closing in favor of #82
