### ISSUE TITLE
`nil` vs `()`

### ISSUE THREAD

**Issue by cpitclaudel** [ejgallego/coq-serapi#8]
In the "issues with serializing to sexps" family, I've just run into the following problem: many lisps do not distinguish between `'()` and `nil`, and thus serialize `()` to `nil`.

For example in common lisp:

```lisp
[7]> (format t "~a" '())
NIL
```

And in Emacs Lisp:

```elisp
(format "%S" `()) ;; => nil 
```

Could we add an option to SerAPI to accept `nil` as a synonym for `()`? Currently I get this:

```
(97 (Query (() None PpStr) Goals))
  (Answer 97 Ack)
  (Answer 97
          (ObjList nil))
(97 (Query (nil None PpStr) Goals))
  (SexpError
   (Sexplib\.Conv\.Of_sexp_error
    (Failure "Sertop_protocol.cmd_of_sexp: unexpected sum tag")
    (97
     (Query
      (nil None PpStr)
      Goals))))
```

<del>In the meantime, I'll look at whether I can make the Emacs lisp printer produce '().</del>

Looking at Emacs' source code, there doesn't seem to be a way to make it print `()` instead of `nil`, but it's pretty easy to write a decent workaround, so I'd call this low priority.

**Comment by ejgallego** [comment]
Indeed, this is handled by `Sexplib`, need to investigate more.

**Comment by ejgallego** [comment]
I'm much afraid that `Sexplib` parser won't be easy to modify to support this use case. I'm sorry.

I propose to tag wontfix for now and try to workaround this bug.

**Comment by cpitclaudel** [comment]
Sounds good. In fact, I'd say we can close this. Here's a small function that will do the trick:

```elisp
(defun prin1-to-sexp (val)
  "Convert VAL to a sexp.
Crucially, renders nil as (), not nil."
  (if (listp val)
      (concat "(" (mapconcat #'prin1-to-sexp val " ") ")")
    (prin1-to-string val)))
```

It breaks if passed an improper list (such as `(1 . 2)`), but that would have confused the sertop side already :)

**Comment by ejgallego** [comment]
Cool, thanks, even if it's a pity to have this minor difference.

Note that this could still be fixed in the future by rolling out our own parser once the whole thing is more stable, so feel free to reopen if needed.

For reference, here are `Sexplib`:

- parser: https://github.com/janestreet/sexplib/blob/master/src/parser.mly
- pretty printer: https://github.com/janestreet/sexplib/blob/master/src/pre_sexp.ml#L174

the last one is interesting as it will determine the escaping done by sertop's printing. I'm not opposed to rolling our own versions if we have good reasons.
